$(document).ready(function(){
	//level1 fade toggle
	$('#link1').click(function(){
		$('#2').hide();
		$('#3').hide();
		$('#4').hide();
		$('#text').hide();
		$('#5').hide();
		$('#6').hide();
		$('#1').fadeIn();
	});
	$('#link2').click(function(){
		$('#5').hide();
		$('#6').hide();
		$('#1').hide();
		$('#3').hide();
		$('#4').hide();
		$('#text').hide();
		$('#2').fadeIn();
	});
	$('#link3').click(function(){
		$('#5').hide();
		$('#6').hide();
		$('#2').hide();
		$('#1').hide();
		$('#4').hide();
		$('#text').hide();
		$('#3').fadeIn();
	});
	$('#link4').click(function(){
		$('#5').hide();
		$('#6').hide();
		$('#2').hide();
		$('#3').hide();
		$('#1').hide();
		$('#text').hide();
		$('#4').fadeIn();
	});
	$('#link5').click(function(){
		$('#4').hide();
		$('#6').hide();
		$('#2').hide();
		$('#3').hide();
		$('#1').hide();
		$('#text').hide();
		$('#5').fadeIn();
	});
	$('#link6').click(function(){
		$('#5').hide();
		$('#4').hide();
		$('#2').hide();
		$('#3').hide();
		$('#1').hide();
		$('#text').hide();
		$('#6').fadeIn();
	});
});